# Generated by Django 4.2.16 on 2024-10-24 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PuntoDeVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_de_venta', to='solicitudes.region')),
            ],
        ),
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_equipo', models.CharField(choices=[('maquinaria', 'Maquinaria'), ('locativo', 'Locativo')], max_length=10)),
                ('nombre_equipo', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_maquinaria', models.CharField(blank=True, choices=[('maquina_helado', 'Máquina de Helado Suave'), ('congelador', 'Congelador'), ('vitrina', 'Vitrina')], max_length=20, null=True)),
                ('tipo_locativo', models.CharField(blank=True, choices=[('muebles', 'Muebles'), ('paredes', 'Paredes'), ('techo', 'Techo'), ('cortinas', 'Cortinas')], max_length=20, null=True)),
                ('punto_de_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activos', to='solicitudes.puntodeventa')),
            ],
        ),
    ]
