# Generated by Django 4.2.16 on 2024-10-16 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='titulo',
        ),
    ]
