# Generated by Django 4.2.16 on 2024-10-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_solicitud_pdv_solicitud_email_solicitant_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrdenTrabajo',
            new_name='GestionOt',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='email_solicitant',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='email_solicitante',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='PDV',
            field=models.CharField(default='', max_length=100),
        ),
    ]
