# Generated by Django 4.2.16 on 2024-10-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0005_rename_ordentrabajo_gestionot'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_solicitud', models.IntegerField()),
                ('tecnico_asignado', models.CharField(max_length=100)),
                ('fecha_actividad', models.DateField()),
                ('estado', models.CharField(default='En Proceso', max_length=50)),
            ],
        ),
    ]
