# Generated by Django 4.2.16 on 2024-10-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0006_ordentrabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estado',
            field=models.CharField(choices=[('solicitudes', 'solicitudes'), ('en proceso', 'OT en Proceso'), ('en revision', 'OT en Revisión'), ('finalizada', 'OT Finalizada')], default='En Proceso', max_length=20),
        ),
    ]
