# Generated by Django 4.2.16 on 2024-10-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0007_alter_ordentrabajo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('solicitudes', 'Solicitudes'), ('en proceso', 'OT en Proceso'), ('en revision', 'OT en Revisión'), ('finalizada', 'OT Finalizada')], default='solicitudes', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estado',
            field=models.CharField(default='En Proceso', max_length=20),
        ),
    ]
