# Generated by Django 4.2.16 on 2024-10-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0008_solicitud_estado_alter_ordentrabajo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fecha_actividad',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
