# Generated by Django 4.2.16 on 2024-10-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0009_alter_ordentrabajo_fecha_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estado',
            field=models.CharField(choices=[('solicitudes', 'Solicitudes'), ('en proceso', 'OT en Proceso'), ('en revision', 'OT en Revisión'), ('finalizada', 'OT Finalizada')], default='en proceso', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fecha_actividad',
            field=models.DateField(),
        ),
    ]
