# Generated by Django 4.2.16 on 2024-10-23 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0012_alter_ordentrabajo_fecha_actividad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
