# Generated by Django 4.2.16 on 2024-10-23 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0013_alter_solicitud_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fecha_actividad',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
